#These are chances of drop from STONE
chances:
  DIAMOND_BLOCK:
    minLevel: 0
    maxLevel: 100
    fortune-0:
      chance: 0.2
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.3
      max-amount: 2
      min-amount: 1
    fortune-2:
      chance: 0.4
      max-amount: 3
      min-amount: 2
    fortune-3:
      chance: 0.5
      max-amount: 4
      min-amount: 3
  EMERALD_BLOCK:
    minLevel: 0
    maxLevel: 100
    fortune-0:
      chance: 0.2
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.3
      max-amount: 2
      min-amount: 1
    fortune-2:
      chance: 0.4
      max-amount: 3
      min-amount: 2
    fortune-3:
      chance: 0.5
      max-amount: 4
      min-amount: 3
  GOLD_BLOCK:
    minLevel: 0
    maxLevel: 100
    fortune-0:
      chance: 0.2
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.3
      max-amount: 2
      min-amount: 1
    fortune-2:
      chance: 0.4
      max-amount: 3
      min-amount: 2
    fortune-3:
      chance: 0.5
      max-amount: 4
      min-amount: 3
  IRON_BLOCK:
    minLevel: 0
    maxLevel: 100
    fortune-0:
      chance: 0.2
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.3
      max-amount: 2
      min-amount: 1
    fortune-2:
      chance: 0.4
      max-amount: 3
      min-amount: 2
    fortune-3:
      chance: 0.5
      max-amount: 4
      min-amount: 3
  LAPIS_LAZULI:
    minLevel: 0
    maxLevel: 100
    fortune-0:
      chance: 0.1
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.2
      max-amount: 2
      min-amount: 1
    fortune-2:
      chance: 0.3
      max-amount: 3
      min-amount: 2
    fortune-3:
      chance: 0.4
      max-amount: 4
      min-amount: 3
  REDSTONE:
    minLevel: 0
    maxLevel: 100
    fortune-0:
      chance: 0.1
      max-amount: 3
      min-amount: 2
    fortune-1:
      chance: 0.2
      max-amount: 4
      min-amount: 3
    fortune-2:
      chance: 0.3
      max-amount: 5
      min-amount: 4
    fortune-3:
      chance: 0.4
      max-amount: 6
      min-amount: 5
  COAL_BLOCK:
    minLevel: 0
    maxLevel: 100
    fortune-0:
      chance: 0.1
      max-amount: 3
      min-amount: 2
    fortune-1:
      chance: 0.2
      max-amount: 4
      min-amount: 3
    fortune-2:
      chance: 0.3
      max-amount: 5
      min-amount: 4
    fortune-3:
      chance: 0.4
      max-amount: 6
      min-amount: 5
  BONE:
    minLevel: 0
    maxLevel: 100
    fortune-0:
      chance: 0.02
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.05
      max-amount: 1
      min-amount: 1
    fortune-2:
      chance: 0.07
      max-amount: 1
      min-amount: 1
    fortune-3:
      chance: 0.1
      max-amount: 1
      min-amount: 1
  WOOD:
    minLevel: 0
    maxLevel: 100
    fortune-0:
      chance: 0.02
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.05
      max-amount: 1
      min-amount: 1
    fortune-2:
      chance: 0.07
      max-amount: 1
      min-amount: 1
    fortune-3:
      chance: 0.1
      max-amount: 1
      min-amount: 1
  ARROW:
    minLevel: 0
    maxLevel: 100
    fortune-0:
      chance: 0.02
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.05
      max-amount: 1
      min-amount: 1
    fortune-2:
      chance: 0.07
      max-amount: 1
      min-amount: 1
    fortune-3:
      chance: 0.1
      max-amount: 1
      min-amount: 1
  STRING:
    minLevel: 0
    maxLevel: 100
    fortune-0:
      chance: 0.02
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.05
      max-amount: 1
      min-amount: 1
    fortune-2:
      chance: 0.07
      max-amount: 1
      min-amount: 1
    fortune-3:
      chance: 0.1
      max-amount: 1
      min-amount: 1
  SLIME_BALL:
    minLevel: 0
    maxLevel: 100
    fortune-0:
      chance: 0.02
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.05
      max-amount: 1
      min-amount: 1
    fortune-2:
      chance: 0.07
      max-amount: 1
      min-amount: 1
    fortune-3:
      chance: 0.1
      max-amount: 1
      min-amount: 1
  TNT:
    minLevel: 0
    maxLevel: 100
    fortune-0:
      chance: 0.02
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.05
      max-amount: 1
      min-amount: 1
    fortune-2:
      chance: 0.07
      max-amount: 1
      min-amount: 1
    fortune-3:
      chance: 0.1
      max-amount: 1
      min-amount: 1
  APPLE:
    minLevel: 0
    maxLevel: 100
    fortune-0:
      chance: 0.02
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.05
      max-amount: 1
      min-amount: 1
    fortune-2:
      chance: 0.07
      max-amount: 1
      min-amount: 1
    fortune-3:
      chance: 0.1
      max-amount: 1
      min-amount: 1
  ENDER_PEARL:
    minLevel: 0
    maxLevel: 100
    fortune-0:
      chance: 0.05
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.07
      max-amount: 1
      min-amount: 1
    fortune-2:
      chance: 0.1
      max-amount: 1
      min-amount: 1
    fortune-3:
      chance: 0.15
      max-amount: 1
      min-amount: 1
  BOOKSHELF:
    minLevel: 0
    maxLevel: 100
    fortune-0:
      chance: 0.1
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.15
      max-amount: 1
      min-amount: 1
    fortune-2:
      chance: 0.2
      max-amount: 1
      min-amount: 1
    fortune-3:
      chance: 0.3
      max-amount: 1
      min-amount: 1
  OBSIDIAN:
    minLevel: 0
    maxLevel: 100
    fortune-0:
      chance: 0.1
      max-amount: 1
      min-amount: 1
    fortune-1:
      chance: 0.2
      max-amount: 1
      min-amount: 1
    fortune-2:
      chance: 0.3
      max-amount: 1
      min-amount: 1
    fortune-3:
      chance: 0.4
      max-amount: 1
      min-amount: 1

#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#This is chance of getting a chest spawned
chest-spawn-chance: 0

#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#And these are possible contents of the chest
chest:
  DIAMOND:
    chance: 0.8
    min: 1
    max: 20
  IRON_INGOT:
    chance: 0.8
    min: 5
    max: 48
  GOLD_INGOT:
    chance: 0.75
    min: 1
    max: 40
  SADDLE:
    chance: 0.1
    min: 1
    max: 1
  GOLDEN_CARROT:
    chance: 1.0
    min: 5
    max: 40
  BLUE_ICE:
    chance: 1.0
    min: 32
    max: 64
  DIAMOND_PICKAXE:
    chance: 0.1
    min: 1
    max: 1
    enchant:
      mending: 1
  FISHING_ROD:
    chance: 0.1
    min: 1
    max: 1
    enchant:
      unbreaking: 3
      lure: 3
      luck_of_the_sea: 3
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#List of commands that could be executed (use @name for player name)
#In this example: 1% chance of executing command give on player.
executeCommands:
  "give @player stick 2": 0.01
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#List of blocks that the plugin should work on. The list of all possible blocks is listed here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
dropBlocks:
  - STONE
  - ANDESITE
  - GRANITE

#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#experience dropped from stone:
experience: 0.3

#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#put here all world that you would like to have disabled:
disabled-worlds:
  - world_nether

#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#Should ores drop items
ore-drop: false
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#If ore-drop is true -> whats the chance to drop item from ore when mining it
ore-drop-chance: 1.0
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#Should the items ne dropped directly into the inventory
drop-to-inventory: true
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#Should display "The plugin has been updated" message
display-update-message: true
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#Should exp be added to player stats or dropped as exp orb - WARNING: in that case experience value has to be >= 1.0
drop-exp-orb: false
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#Should a message be broadcast when a player finds a chest
treasure-broadcast: true
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#Volume of all sounds used in the plugin
volume: 0.3
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
#Drop chest contents to inventory
drop-chest-to-inventory: false